name: Github Actions demo
on: [push]
jobs:
  Demo-github-actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job is running on ${{ runner.os }}"
      - run: echo "Running from branch ${{ github.ref }} in repository ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "Job status is ${{ job.status }}"
      - name: Install virtualenv
        run: |
          pip3 install virtualenv
      - name: Set up virtualenv
        run: |
          virtualenv --python=python3 venv
          venv/bin/pip install -r requirements.txt
      - name: Run tests
        run: |
          venv/bin/pytest --junit-xml=testresults.xml test.py
