name: Issues test

on: [issues]

jobs:
  welcome-new-user:
    runs-on: ubuntu-latest
    steps:
      - name: First interaction
        uses: actions/first-interaction@v1.1.0
        with:
          # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
          repo-token: "{{ secrets.GITHUB_TOKEN }}"
          # Comment to post on an individual's first issue
          issue-message: "Glad to have you here, thank you for filing your first issue!"
          # Comment to post on an individual's first pull request
          pr-message: "Thank you for your contribution!"
